create table if not exists public.meal_plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  plan_date date not null,
  breakfast_recipe_id bigint references public.recipes (id) on delete set null,
  snack_recipe_id bigint references public.recipes (id) on delete set null,
  lunch_recipe_id bigint references public.recipes (id) on delete set null,
  dinner_recipe_id bigint references public.recipes (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint meal_plans_user_id_plan_date_unique unique (user_id, plan_date)
);

alter table public.meal_plans
add column if not exists snack_recipe_id bigint references public.recipes (id) on delete set null;

create index if not exists meal_plans_user_id_plan_date_idx
  on public.meal_plans (user_id, plan_date desc);

create or replace function public.set_updated_at_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_meal_plans_updated_at on public.meal_plans;
create trigger trg_meal_plans_updated_at
before update on public.meal_plans
for each row
execute function public.set_updated_at_timestamp();

alter table public.meal_plans enable row level security;

grant select, insert, update, delete on table public.meal_plans to authenticated;
grant usage, select on sequence public.meal_plans_id_seq to authenticated;

drop policy if exists "meal_plans_select_own" on public.meal_plans;
create policy "meal_plans_select_own"
on public.meal_plans
for select
using (auth.uid() = user_id);

drop policy if exists "meal_plans_insert_own" on public.meal_plans;
create policy "meal_plans_insert_own"
on public.meal_plans
for insert
with check (
  auth.uid() = user_id
  and (breakfast_recipe_id is null or exists (
    select 1
    from public.recipes r
    where r.id = breakfast_recipe_id
      and (r.is_public or r.owner_user_id = auth.uid())
  ))
  and (snack_recipe_id is null or exists (
    select 1
    from public.recipes r
    where r.id = snack_recipe_id
      and (r.is_public or r.owner_user_id = auth.uid())
  ))
  and (lunch_recipe_id is null or exists (
    select 1
    from public.recipes r
    where r.id = lunch_recipe_id
      and (r.is_public or r.owner_user_id = auth.uid())
  ))
  and (dinner_recipe_id is null or exists (
    select 1
    from public.recipes r
    where r.id = dinner_recipe_id
      and (r.is_public or r.owner_user_id = auth.uid())
  ))
);

drop policy if exists "meal_plans_update_own" on public.meal_plans;
create policy "meal_plans_update_own"
on public.meal_plans
for update
using (auth.uid() = user_id)
with check (
  auth.uid() = user_id
  and (breakfast_recipe_id is null or exists (
    select 1
    from public.recipes r
    where r.id = breakfast_recipe_id
      and (r.is_public or r.owner_user_id = auth.uid())
  ))
  and (snack_recipe_id is null or exists (
    select 1
    from public.recipes r
    where r.id = snack_recipe_id
      and (r.is_public or r.owner_user_id = auth.uid())
  ))
  and (lunch_recipe_id is null or exists (
    select 1
    from public.recipes r
    where r.id = lunch_recipe_id
      and (r.is_public or r.owner_user_id = auth.uid())
  ))
  and (dinner_recipe_id is null or exists (
    select 1
    from public.recipes r
    where r.id = dinner_recipe_id
      and (r.is_public or r.owner_user_id = auth.uid())
  ))
);

drop policy if exists "meal_plans_delete_own" on public.meal_plans;
create policy "meal_plans_delete_own"
on public.meal_plans
for delete
using (auth.uid() = user_id);
